import { ArrowDownUp, TrendingUp } from "lucide-react";
import SurfaceCard from "../../components/common/SurfaceCard";
import { SYMBOLS } from "../../config/contracts";

export default function PriceOverviewCard({ ammData }) {
  return (
    <SurfaceCard variant="panel" className="flex min-h-[330px] flex-col p-5">
      <div className="flex items-start justify-between gap-4">
        <div>
          <div className="dex-chip">Live Quote</div>
          <h3 className="mt-3 text-xl font-black text-[var(--text)]">
            Market Price
          </h3>
          <p className="mt-1 text-sm text-[var(--muted)]">
            Price is generated by reserve ratio, not manually set.
          </p>
        </div>

        <div className="grid h-12 w-12 place-items-center rounded-2xl bg-[var(--blue-soft)] text-[var(--blue)]">
          <TrendingUp size={22} />
        </div>
      </div>

      <div className="mt-5 rounded-[22px] border border-[var(--success-border)] bg-[var(--success-soft)] p-5">
        <p className="text-xs font-black uppercase tracking-wide text-[var(--muted)]">
          {SYMBOLS.tokenA} / {SYMBOLS.tokenB}
        </p>
        <p className="mt-2 text-3xl font-black market-up">
          {ammData.priceAinB}
          <span className="ml-2 text-base">{SYMBOLS.tokenB}</span>
        </p>
      </div>

      <div className="mt-4 grid gap-3">
        <PriceRow
          label={`${SYMBOLS.tokenB} / ${SYMBOLS.tokenA}`}
          value={`${ammData.priceBinA} ${SYMBOLS.tokenA}`}
        />
        <PriceRow label="Swap Fee" value="0.3%" tone="warning" />
        <PriceRow
          label="Pricing Model"
          value="x · y = k"
          icon={<ArrowDownUp size={14} />}
        />
      </div>
    </SurfaceCard>
  );
}

function PriceRow({ label, value, tone = "neutral", icon }) {
  const color =
    tone === "warning" ? "market-warning" : "text-[var(--text)]";

  return (
    <div className="dex-stat flex items-center justify-between gap-4">
      <div className="flex items-center gap-2 text-sm font-bold text-[var(--muted)]">
        {icon}
        {label}
      </div>
      <span className={`max-w-[170px] truncate text-right text-sm font-black ${color}`}>
        {value}
      </span>
    </div>
  );
}